
CREATE USER "test_user" WITH PASSWORD 'letmein' NOSUPERUSER INHERIT CREATEROLE;

CREATE DATABASE "test_db" WITH OWNER = "test_user" ENCODING "UTF8";

GRANT ALL PRIVILEGES ON DATABASE "test_db" TO "test_user";

